### ISSUE TITLE
Pypi release is missing test_mccabe.py

### ISSUE THREAD

**Issue by tamentis** [flintwork/mccabe#31]
I was updating a port of mccabe and noticed that `test_mccabe.py` was missing from the Pypi release.

**Comment by sigmavirus24** [comment]
@tamentis it never shipped with the release.

**Comment by tamentis** [comment]
Yup, I can see that. The change log mentions the added tests for 0.3 so I was planning on adding that as part of the port in OpenBSD. For most Python ports, the test suite runs but I guess we'll skip it for mccabe 0.3.

**Comment by sigmavirus24** [comment]
You can still pull it in, I just don't see much value in including it in the PyPI package. Is it really necessary the the tests be included in the package itself?

**Comment by tamentis** [comment]
You're right, I can pull it in and test it locally.

Adding test suites to official releases means they are likely to be run as part of the packaging systems and will be executed on thousands of machine, on various architectures and operating systems and could find bugs in places authors never imagined :)

However mccabe doesn't have dependencies, its test suite is tiny and new, so it doesn't matter as much. If I really wanted it, I could just base the port from the github tag, but I'll just skip the test suite for the OpenBSD package.

**Comment by floppym** [comment]
Speaking as a Linux distro maintainer, we would prefer that you include the tests in the pypi tarball so that we don't have to piece together sources from multiple locations. The extra bytes won't hurt anyone.

**Comment by sigmavirus24** [comment]
Fixed by https://github.com/flintwork/mccabe/commit/eb9df5f800e1c70099d64a809ff3a6700fe0e160
