### ISSUE TITLE
max-complexity overwritten with string or bool in pep8.py

### ISSUE THREAD

**Issue by PyGuy2** [flintwork/mccabe#32]
Using flake8, mccabe and setuptools leads to setting wrong max_complexity option.

When you set setup.cfg to
```config
[flake8]
max-complexity = 2
``` 
the command 
```shell
./setup.py flake8 
```
will not produce correct output, while calling
```shell
flake8
```
does.

Setting it to max-complexity=1 works, but the type of the option is set to boolean. When set to 2 it's a string instead of the requested int thus leading to always False comparisons at the mccabe code.

The option is parsed correctly at pep8 but is overwritten at pep8.py in class StyleGuide:1629:
```python
       if options_dict:
            options.__dict__.update(options_dict)
```

I don't know if the problem lies in the mccabe code, pep8 or flake8, so reporting it here.

Versions used:

Python 2.7.6

argparse (1.2.1)
autopep8 (0.9.1)
coverage (3.7.1)
flake8 (2.4.0)
matplotlib (1.3.1)
mccabe (0.3)
nose (1.3.1)
numpy (1.8.2)
pandas (0.13.1)
pep8 (1.5.7)
pexpect (3.1)
Pillow (2.3.0)
pip (1.5.4)
ply (3.4)
Pmw (1.3.2)
pyflakes (0.8.1)
Pygments (1.6)
pyinotify (0.9.4)
pyparsing (2.0.1)
python-dateutil (1.5)
pytz (2012c)
PyX (0.12.1)
requests (2.2.1)
ScientificPython (2.9.4)
scikit-learn (0.14.1)
scipy (0.13.3)
SciTools (0.9.0)
setuptools (2.2)
Shapely (1.3.0)
simplegeneric (0.8.1)
simplejson (3.3.1)
six (1.5.2)
SQLAlchemy (0.8.4)
ssh-import-id (3.21)
statsmodels (0.5.0)
sympy (0.7.4.1)
tables (3.1.1)
Twisted-Core (13.2.0)
UFL (1.5.0)
urllib3 (1.7.1)
virtualenv (1.11.4)
VTK (5.8.0)
Werkzeug (0.9.4)
wheel (0.24.0)
wsgiref (0.1.2)
xlrd (0.9.2)
xlwt (0.7.5)

**Comment by PyGuy2** [comment]
changing  mccabe.py from
```python
    @classmethod
    def parse_options(cls, options):
        cls.max_complexity = options.max_complexity
```
to 
```python
    @classmethod
    def parse_options(cls, options):
        cls.max_complexity = int(options.max_complexity)
```

might fix the problem.

**Comment by sigmavirus24** [comment]
Since pep8 and flake8 handles the config file parsing and such, I'm thinking this might be something that we should fix there. Does that make sense to you @PyGuy2 ?

**Comment by sigmavirus24** [comment]
Also, sorry that I completely missed this before today

**Comment by PyGuy2** [comment]
@sigmavirus24 I'm fine with that... until it's fixed one might find a temporary fix here. 
It's even worst. It's somewhere in the setuptools - flake8 API handling...

**Comment by PyGuy2** [comment]
could you report it upstream?

**Comment by sigmavirus24** [comment]
@PyGuy2 you should be able to upgrade mccabe and get this fix.
